import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from '@/components/providers';
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: process.env.TITLE ?? "FinanClub",
  description: process.env.DESC ?? "Generated by create next app",
};

// Function to fetch categories from Notion

// Main layout component
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Fetch categories

  return (
    <html lang="en">
      <head>
        {process.env.NEXT_PUBLIC_ADSENSE_P_ID && (
          <Script
            async
            src={`https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-${process.env.NEXT_PUBLIC_ADSENSE_P_ID}`}
            crossOrigin='anonymous'
            strategy='afterInteractive'
          />
        )}
      </head>
      <body className={inter.className}>
        <Providers
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
            {children}
        </Providers>
      </body>
    </html>
  );
}